# Generated by Django 4.0 on 2021-12-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, verbose_name='Version del Software')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca del Software')),
            ],
        ),
    ]
