# Generated by Django 4.0 on 2021-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='so',
            options={'verbose_name_plural': 'Softwares'},
        ),
        migrations.AddField(
            model_name='so',
            name='tipo',
            field=models.CharField(default='', max_length=100, verbose_name='Tipo de Software'),
        ),
    ]
