# Generated by Django 4.0 on 2021-12-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_so_options_so_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='so',
            options={'verbose_name_plural': 'Softwars'},
        ),
        migrations.AlterField(
            model_name='so',
            name='version',
            field=models.CharField(max_length=100, unique=True, verbose_name='Version del Software'),
        ),
    ]
