# Generated by Django 4.0 on 2021-12-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del UPS')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de UPS')),
                ('inventario', models.CharField(max_length=100, verbose_name='Inventario de UPS')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la UPS')),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Teclado')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Teclado')),
                ('inventario', models.CharField(max_length=100, verbose_name='Invenatrio de Teclado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Teclado')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Monitor')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Monitor')),
                ('inventario', models.CharField(max_length=100, verbose_name='Inventario de Monitor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Monitor')),
            ],
        ),
        migrations.CreateModel(
            name='Mause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Mause')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Mause')),
                ('invenatrio', models.CharField(max_length=100, verbose_name='Inventario de Mause')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Mause')),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Impresora')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Impresora')),
                ('inventario', models.CharField(max_length=100, verbose_name='Inventario de Impresora')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Impresora')),
            ],
        ),
        migrations.CreateModel(
            name='Chasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Chasis')),
                ('ns', models.CharField(max_length=100, verbose_name='Numero de serie del Chasis')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca del Chasis')),
            ],
        ),
        migrations.CreateModel(
            name='Bocinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Bocinas')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Bocinas')),
                ('inventario', models.CharField(max_length=100, verbose_name='Inventario de Bocinas')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Bocinas')),
            ],
        ),
    ]
