# Generated by Django 4.0 on 2021-12-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perifericos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mause',
            old_name='invenatrio',
            new_name='inventario',
        ),
    ]
