# Generated by Django 4.0 on 2021-12-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perifericos', '0002_rename_invenatrio_mause_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasis',
            name='inv',
            field=models.CharField(default='', max_length=100, verbose_name='Numero de Inventario'),
        ),
    ]
