# Generated by Django 4.0 on 2021-12-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perifericos', '0003_chasis_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chasis',
            name='inv',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Numero de Inventario'),
        ),
    ]
