# Generated by Django 4.0 on 2021-12-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del MotherBoard')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial del MotherBoard')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Mother Board')),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Memoria')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Memoria')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de la Memoria Ram')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Memoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Fuente')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Fuente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Fuente')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoDuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Disco')),
                ('ns', models.CharField(max_length=100, verbose_name='Serial de Disco')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de la Disco')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca de la Disco')),
            ],
            options={
                'verbose_name_plural': 'Discos Duros',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.CharField(max_length=100, verbose_name='Datos Generales del Micro procesador')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.marca', verbose_name='Marca del Procesador')),
            ],
        ),
    ]
