# Generated by Django 4.0 on 2021-12-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name_plural': 'CPU'},
        ),
        migrations.AlterModelOptions(
            name='memoriaram',
            options={'verbose_name_plural': 'Memorias Ram'},
        ),
        migrations.AlterModelOptions(
            name='placabase',
            options={'verbose_name_plural': 'Mother Boards'},
        ),
    ]
