# Generated by Django 4.0 on 2021-12-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componentes', '0001_initial'),
        ('config', '0001_initial'),
        ('software', '0001_initial'),
        ('perifericos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion del Expediente')),
                ('inv_torre', models.CharField(max_length=100, verbose_name='Inventario de la Torre')),
                ('sello', models.CharField(max_length=100, unique=True, verbose_name='Sello de PC')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.departamento', verbose_name='Area de la PC')),
                ('bocinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perifericos.bocinas', verbose_name='Bocinas Duro de la PC')),
                ('chasis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perifericos.chasis', verbose_name='Chasis de la PC')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.cpu', verbose_name='CPU de la PC')),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perifericos.impresora', verbose_name='Impresora de la PC')),
                ('mause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perifericos.mause', verbose_name='Mause de la PC')),
                ('mb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.placabase', verbose_name='Mother Board de la PC')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.memoriaram', verbose_name='Memoria Ram de la PC')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perifericos.monitor', verbose_name='Monitor de la PC')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.so', verbose_name='Sistema Operativo  de la PC')),
                ('teclado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perifericos.teclado', verbose_name='Teclado de la PC')),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perifericos.ups', verbose_name='UPS de la PC')),
            ],
        ),
    ]
