# Generated by Django 4.0 on 2021-12-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Numeo de Expediente'),
        ),
    ]
