# Generated by Django 4.0 on 2021-12-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_pc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='otros',
            field=models.CharField(default='', max_length=255, verbose_name='Otros Datos de Interes'),
        ),
    ]
